name: build

on: [push]

env:
  LIBSODIUM: libsodium-1.0.18

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache libsodium
      id: cache-libsodium
      uses: actions/cache@v2
      with:
        path: libsodium-1.0.18
        key: ${{ runner.os }}-libsodium-1.0.18

    - name: Cache lz4
      id: cache-lz4
      uses: actions/cache@v2
      with:
        path: lz4-1.9.3
        key: ${{ runner.os }}-lz4-1.9.3

    - name: Cache Cargo
      id: cache-cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build libsodium
      if: steps.cache-libsodium.outputs.cache-hit != 'true'
      run: |
        wget -nv https://download.libsodium.org/libsodium/releases/$LIBSODIUM.tar.gz
        tar -xzf $LIBSODIUM.tar.gz
        cd $LIBSODIUM && ./configure --prefix=/usr && make

    - name: Install libsodium
      run: cd $LIBSODIUM && sudo make install

    - name: Build lz4
      if: steps.cache-lz4.outputs.cache-hit != 'true'
      run: |
        wget -nv https://github.com/lz4/lz4/archive/refs/tags/v1.9.3.tar.gz
        tar -xzf v1.9.3.tar.gz
        cd lz4-1.9.3 && make lib-release

    - name: Install lz4
      run: cd lz4-1.9.3 && sudo make install

    - name: Build ZboxFS
      run: cargo build

    - name: Run ZboxFS tests
      run: cargo test

    - name: Run ZboxFS file storage tests
      run: cargo test --features storage-file

  build-win:
    runs-on: windows-latest
    env:
      SODIUM_LIB_DIR: D:\a\zbox\zbox\libsodium-1.0.18\x64\Release\v142\static
      SODIUM_STATIC: 1

    steps:
    - uses: actions/checkout@v2

    - name: Cache libsodium
      id: cache-libsodium
      uses: actions/cache@v2
      with:
        path: libsodium-1.0.18
        key: ${{ runner.os }}-libsodium-1.0.18

    - name: Download libsodium
      if: steps.cache-libsodium.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest https://download.libsodium.org/libsodium/releases/${env:LIBSODIUM}-msvc.zip -OutFile ${env:LIBSODIUM}-msvc.zip
        Expand-Archive ${env:LIBSODIUM}-msvc.zip -DestinationPath ${env:LIBSODIUM}

    - name: Build ZboxFS
      run: echo %GITHUB_WORKSPACE% && dir && cargo build -q

    - name: Run ZboxFS tests
      run: cargo test

    - name: Run ZboxFS file storage tests
      run: cargo test --features storage-file
